package ;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

public class MapProjectController {

	// Event Listener on Button[#NAButton].onAction
	@FXML
	public void NAButtonClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#SAButton].onAction
	@FXML
	public void SAButtonClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#AntBUtton].onAction
	@FXML
	public void AntButtonClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#AfricaButton].onAction
	@FXML
	public void AfricaButtonClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#EUButton].onAction
	@FXML
	public void EUButtonClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#AsiaButton].onAction
	@FXML
	public void AsiaButtonClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#AusBUtton].onAction
	@FXML
	public void AusButtonClicked(ActionEvent event) {
		// TODO Autogenerated
	}
}
